### ISSUE TITLE
nothing being published in the /scan topic

### ISSUE THREAD

**Issue by Aswath93** [ros-perception/depthimage_to_laserscan#17]
Hey,

I have written a launch file to map the right topics correspondingly, but nothing is being published on /scan topic.  could someone help me fix this?

thanks

this is the launch file i used:

```
<launch>

<node pkg="depthimage_to_laserscan" type="depthimage_to_laserscan" name="depthimage_to_laserscan">


  <remap from="image" to="/guidance/depth_image"/>
<remap from="camera_info" to="/guidance/camera_info"/>
</node>

</launch>
```

**Comment by tfoote** [comment]
Please ask for help on http://answers.ros.org We try to reserve issues for bugs or feature requests. See our support policy http://wiki.ros.org/Support
