### ISSUE TITLE
Does it work with Kinect v2?

### ISSUE THREAD

**Issue by pallavbakshi** [ros-perception/depthimage_to_laserscan#19]
Hi,

Does it work with Kinect v2? What code modifications I can make to make it work, if possible?

Thanks,
Pallav

**Comment by tfoote** [comment]
It should work with anything that produces a depth image. Please ask questions on http://answers.ros.org We try to reserve issues for bugs or feature requests. See our support policy http://wiki.ros.org/Support

**Comment by pallavbakshi** [comment]
Thanks! I will take care about that in the future. However, can you link your ROS account to github repo as well.
