### ISSUE TITLE
Couldn't create laser scan equivalent to that of the Hokuyo Lidar (for front part of the vehicle)

### ISSUE THREAD

**Issue by AmeyHande** [ros-perception/depthimage_to_laserscan#33]
Hello Everyone,
I'm new to depth image and laser scan data usage. I'm trying to use laser scan data obtained from Depth data of ZED Stereo camera. It's axis configuration in the PointCloud2 data is as per this description [https://www.stereolabs.com/docs/positional-tracking/coordinate-frames/](url) and launch file which I'm using on ROS Melodic, Ubuntu 18.04, Nvidia Jetson Xavier is as follows
`<launch>
    <node pkg="depthimage_to_laserscan" type="depthimage_to_laserscan" name="DepthImageToLaserScanNodelet">
      <remap from="image" to="/zed/depth/depth_registered"/>
      <remap from="camera_info" to="/zed/depth/camera_info"/>
      <remap from="scan" to="/scan" />
      <rosparam>
        scan_height: 1
        scan_time: 0.0333
        range_min: 0.3
        range_max: 10.0
      </rosparam>
    </node>
</launch>`
Branch of depthimage_to_laserscan which I'm using is of @mikaelarguedas .
I think I need to include output_frame_id as well, but not sure how to decide value of this parameter.
Any help would be greatly appreciated.

**Comment by clalancette** [comment]
We ask that you kindly ask these kind of support questions on https://answers.ros.org.  That way all of the answers are in one place and are searchable in the future.  I'm going to close this out, but feel free to keep commenting or reopen if you think this is a bug in this package.
