### ISSUE TITLE
gampping :depthimage_tolaserscan give error (Scan Matching Failed, using odometry. Likelihood=0)

### ISSUE THREAD

**Issue by q8wwe** [ros-perception/depthimage_to_laserscan#35]
trying to use depthimage_to _laserscan with gmapping but i got the mentioned error .

in here original topic
 https://answers.ros.org/question/311741/depthimage_to_laserscankinect-gmapping-give-error-scan-matching-failed-using-odometry-likelihood0/

**Comment by clalancette** [comment]
It looks like the conversation went on in the answers.ros.org post, so I'm going to close this out.
