### ISSUE TITLE
No rule to make target '/usr/lib/aarch64-linux-gnu/libopencv_objdetect.so.3.2.0'

### ISSUE THREAD

**Issue by Tengyun-Mo** [ros-perception/depthimage_to_laserscan#41]
My platform is Jetson TX2 with jetpack 4.2, ros melodic. When I use catkin_make to make depthimage_to_laserscan, there is an error.

`make[2]: *** No rule to make target '/usr/lib/aarch64-linux-gnu/libopencv_objdetect.so.3.2.0', needed by '/home/sikong/catkin_ws/devel/lib/libDepthImageToLaserScan.so'.  Stop.`

**Comment by Tengyun-Mo** [comment]
I try to run this` sudo apt-get install ros-melodic-depthimage-to-laserscan`to solve the issue,but I still get the error.I don't find libopencv_objdetect.so.3.2.0 under the file `/usr/lib/aarch64-linux-gnu/`,I guess it will be fixed by copying  libopencv_objdetect.so.3.2.0 to /usr/lib/aarch64-linux-gnu/.Who can show me the libopencv_objdetect.so.3.2.0,I will very appreciate it,thanks.

**Comment by Jetson999** [comment]
you need again Compile Opencv 3.2.0:
 `cmake ..`
 `make`
`sudo make install`

**Comment by clalancette** [comment]
Yes, @haosen9527 generally has it right.  Usually this means that OpenCV wasn't installed correctly.

As an FYI, on Ubuntu 18.04, you need to have the package `libopencv-objdetect3.2` installed for this to work.

I'm going to close this out, but feel free to keep commenting or re-open if you still are having problems.

**Comment by atmagopal** [comment]
Commenting just to post the solution I found in https://github.com/AprilRobotics/apriltag_ros/issues/66#issuecomment-578309418 for the exact same issue

`sudo apt install libopencv3.2`

This installs the missing libraries, including libopencv_objdetect.so.3.2.0.

**Comment by AndreV84** [comment]
won't it work with opencv 4.1?
