### ISSUE TITLE
Release for Noetic

### ISSUE THREAD

**Issue by Michael-Equi** [ros-perception/depthimage_to_laserscan#49]
If anyone is able to port this over it would be greatly appreciated. I can build from source for noetic on 20.04 fine so a release should not be much trouble.

http://wiki.ros.org/noetic/Migration

**Comment by YannickdeHoop** [comment]
@chadrockey, We would like to have a noetice release also.

**Comment by clalancette** [comment]
I've gone ahead and done a release into Noetic: https://github.com/ros/rosdistro/pull/28803

**Comment by blackjacket996** [comment]
@clalancette Hey bro, Sorry to say that I did not understand how to use your repo, could you please explain it?
