### ISSUE TITLE
release 1.0.5 into groovy

### ISSUE THREAD

**Issue by tfoote** [ros-perception/depthimage_to_laserscan#5]
It's breaking now: http://jenkins.ros.org/view/GbinP32/job/ros-groovy-depthimage-to-laserscan_binarydeb_precise_i386/61/console

[ 40%] Building CXX object CMakeFiles/DepthImageToLaserScanROS.dir/src/DepthImageToLaserScanROS.cpp.o
/usr/lib/ccache/c++   -DDepthImageToLaserScanROS_EXPORTS -DROS_PACKAGE_NAME=\"depthimage_to_laserscan\" -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security  -fPIC -I/tmp/buildd/ros-groovy-depthimage-to-laserscan-1.0.4-0precise-20130923-0603/obj-i686-linux-gnu/devel/include -I/tmp/buildd/ros-groovy-depthimage-to-laserscan-1.0.4-0precise-20130923-0603/include -I/opt/ros/groovy/include -I/opt/ros/groovy/include/opencv    -o CMakeFiles/DepthImageToLaserScanROS.dir/src/DepthImageToLaserScanROS.cpp.o -c /tmp/buildd/ros-groovy-depthimage-to-laserscan-1.0.4-0precise-20130923-0603/src/DepthImageToLaserScanROS.cpp
In file included from /tmp/buildd/ros-groovy-depthimage-to-laserscan-1.0.4-0precise-20130923-0603/src/DepthImageToLaserScanROS.cpp:34:0:
/tmp/buildd/ros-groovy-depthimage-to-laserscan-1.0.4-0precise-20130923-0603/include/depthimage_to_laserscan/DepthImageToLaserScanROS.h:43:49: fatal error: depthimage_to_laserscan/DepthConfig.h: No such file or directory

**Comment by chadrockey** [comment]
@tfoote What changed in Groovy to break code?  :(  Something in dynamic_reconfigure?

**Comment by chadrockey** [comment]
@tfoote Both 1.04 and 1.05 build for me in a Groovy workspace from shadow-fixed.  Is there something I can do to reproduce this locally?

**Comment by tfoote** [comment]
It's a race condition which was exposed by a recent cleanup of the cmake associated with dynamic_reconfigure.  It used to be that dynamic_reconfigure both generated at cmake time and at build time (https://github.com/ros/dynamic_reconfigure/pull/15).  It's been cleaned up to only generate at build time.  Thus if you don't have  a dependency on the generated configs your the *Config.h is not guaranteed to have been generated before you compile.

**Comment by chadrockey** [comment]
Ah got it, thanks for the update.

I released 1.05 into groovy and it looks like it's building.
https://github.com/ros/rosdistro/pull/2257

http://www.ros.org/debbuild/groovy.html
