### ISSUE TITLE
Some questions about the project running

### ISSUE THREAD

**Issue by STRIVESS** [ros-perception/depthimage_to_laserscan#52]
Excuse me，I  have  successfully installed  ROS kinetic and Astra Mini webcam driver[Ubuntu16.04在ROS kinetic下使用Astra Mini摄像头](https://blog.csdn.net/weixin_37933097/article/details/115693741)，I download the code in the Ubuntu 16.04 and I follow this website [Linux环境下载github项目并运行](https://blog.csdn.net/litongqiang/article/details/88558905#commentBox) to operate.However，I meet some problems during the Eighth step and  
report error：make: *** No targets specified and no makefile found.  Stop.
So  how do I run this program in the  Ubuntu 16.04 ?

**Comment by clalancette** [comment]
Please ask questions like this on https://answers.ros.org, and give a lot of detail on what you have tried and the exact error that you are getting.  That way the answers are in one, searchable place.

I'm going to close this out.
