### ISSUE TITLE
If i want to rotate camera 90 degree, how can i use this package?

### ISSUE THREAD

**Issue by lemon5254** [ros-perception/depthimage_to_laserscan#53]
Excuse me, if i want to find minimum depth of each x axis to be the laserscan data , how can i change the code?

**Comment by clalancette** [comment]
For questions like this, please ask them on https://answers.ros.org, and give a lot of detail about what you are trying to do, with what ROS distribution, etc.  That way answers are all in one, searchable location.

I'm going to close this one out for now.
