### ISSUE TITLE
depthimage_to_laserscan didn't work with rs_d400_and_t265

### ISSUE THREAD

**Issue by giry-ankoro** [ros-perception/depthimage_to_laserscan#57]
Hi ! 
I wanted to use depthimage_to_laserscan package with rs_d400_and_t265_launch.py on my realsense cameras. But it didn't work at all.

Interestingly, this package somehow worked with rs_launch.py,  so I guess that is the problem about topic.....

I'm not used to ROS2 and I don't know how to deal with this problem.

Thank you for the help!!

https://github.com/IntelRealSense/realsense-ros/tree/foxy

**Comment by clalancette** [comment]
This sounds like a mis-configuration about topics, either with the topic name or with the quality-of-service settings.  I'll suggest you post a question to https://answers.ros.org with your exact setup, how you tried to run it, and what happened.  You should be able to get some better answers there.

**Comment by giry-ankoro** [comment]
Thank you so much, I really appreciated it!!
