### ISSUE TITLE
Out of range become nan instead of inf.

### ISSUE THREAD

**Issue by TeerapongPoom** [ros-perception/depthimage_to_laserscan#61]
I read in the wiki https://wiki.ros.org/depthimage_to_laserscan and it says ranges less than `range_min` will be output as -Inf and +Inf for `range_max`.
When I try with `range_min=0.3` and `range_max=4.0`, all values not in range become nan. Here is message from rostopic echo https://drive.google.com/file/d/1YSh61ATBp4Xuy6y_YcDfNicW1LBbvW1E/view?usp=sharing

But this is the result after I increase range_max to `range_max=10.0`
https://drive.google.com/file/d/1Vnczgholi2ksoAOVkHGeTYrr4JSMgLlA/view?usp=sharing

My sensor is realsense d455 and depth image encoding is 16UC1. 
ROS distro in noetic. This is how i call node in launch file.
>>> <launch>
    <node pkg="depthimage_to_laserscan" type="depthimage_to_laserscan" name="depthimage_to_laserscan">
      <remap from="image"       to="/camera/depth/image_rect_raw"/>
      <remap from="camera_info" to="/camera/depth/camera_info"/>
      <remap from="scan"        to="/depth_scan"/>
      <param name="range_max" type="double" value="4.0"/>
      <param name="range_min" type="double" value="0.3"/>
      <param name="output_frame_id" type="string" value="camera_link"/>
    </node>
</launch>

**Comment by TeerapongPoom** [comment]
nvm. I just add
```
if(r > scan_msg->range_max){
  scan_msg->ranges[index] = std::numeric_limits<float>::infinity();
}
```
to line 208 in DepthImageToLaserScan.h and it works now.

**Comment by nakai-omer** [comment]
@TeerapongPoom This is an important bug, that breaks costmaps in nav2. I think it should be reopened so it will be fixed for everyone.
