### ISSUE TITLE
Node Dies Soon After Launch

### ISSUE THREAD

**Issue by RNorlie** [ros-perception/depthimage_to_laserscan#62]
I installed the Foxy-devel branch
I'm on a Jetson Xavier NX running ubuntu 20.04, and when I launch the node, it dies almost immediately. 

```
[INFO] [launch]: All log files can be found below /home/jetson_dev/.ros/log/2022-06-17-14-24-10-925028-jetson-dev-desktop-12216
[INFO] [launch]: Default logging verbosity is set to INFO
/home/jetson_dev/ros2_ws/install/depthimage_to_laserscan/share/depthimage_to_laserscan/launch/depthimage_to_laserscan-launch.py:27: UserWarning: The parameter 'node_executable' is deprecated, use 'executable' instead
  Node(
/home/jetson_dev/ros2_ws/install/depthimage_to_laserscan/share/depthimage_to_laserscan/launch/depthimage_to_laserscan-launch.py:27: UserWarning: The parameter 'node_name' is deprecated, use 'name' instead
  Node(
[INFO] [depthimage_to_laserscan_node-1]: process started with pid [12219]
[ERROR] [depthimage_to_laserscan_node-1]: process has died [pid 12219, exit code -11, cmd '/home/jetson_dev/ros2_ws/install/depthimage_to_laserscan/lib/depthimage_to_laserscan/depthimage_to_laserscan_node --ros-args -r __node:=depthimage_to_laserscan_node -r __node:=depthimage_to_laserscan_node --params-file /home/jetson_dev/ros2_ws/install/depthimage_to_laserscan/share/depthimage_to_laserscan/cfg/param.yaml -r depth:=/camera/depth/image_rect_raw -r depth_camera_info:=/camera/depth/camera_info'].
```

Is there any way I can keep the node running?

**Comment by clalancette** [comment]
The exit code -11 means that the process is crashing.

On my Foxy container, I can successfully run:

```
$ ros2 launch depthimage_to_laserscan depthimage_to_laserscan-launch.py
```

That said, I have no data coming in, and I don't have the same parameters set as you do.

What I would suggest is a few things:
1. Try using the packaged `depthimage_to_laserscan`, rather than building it from source, and see if that works better.
2. Try out the simple launch file like I launched above, and see if it stays up for you.
3. Attach the parameters you are using for this node to this ticket, since it seems like they are different than the default.
4. If it is still crashing after that, you may have to attach a debugger to it and get a stack trace.

**Comment by RNorlie** [comment]
Thank you for your response.

I just did some troubleshooting, and I found that the issue was I had a camera node running in the background which caused this node to crash. 

If I run the depthimage_to_laserscan node without any data coming in, it will stay open, but once I launch a realsense-ros camera node, then it crashes.

I'll give the packaged version a go.
Thanks!

**Comment by clalancette** [comment]
All right, sounds good.

The node really shouldn't crash on incoming data (even if it is malformed), so if you can figure out what is causing it to crash we can certainly try to make it more robust.

**Comment by RNorlie** [comment]
I'm fairly new to ROS and linux, so my diagnostic skills are not the sharpest.

Is there any information I could provide to help figure it out?

**Comment by RNorlie** [comment]
Update on the issue:

I don't think I properly installed the package, and I was still utilizing the foxy-devel branch code. When attempting a fresh install, I am unable to build the package. Apologies, as I suspect this is simply a linux-beginner question. Am I installing this software correctly?

I performed `git clone https://github.com/ros-perception/depthimage_to_laserscan.git -b ros2`, rosdep update and install, and when I try to build it, I receive the following error:

```
jetson_dev@jetson-dev-desktop:~/ros2_ws$ colcon build --packages-select depthimage_to_laserscan
Starting >>> depthimage_to_laserscan
--- stderr: depthimage_to_laserscan                    	 
CMake Error at CMakeLists.txt:37 (add_library):
  Target "DepthImageToLaserScanROS" links to target
  "rclcpp_components::component" but the target was not found.  Perhaps a
  find_package() call is missing for an IMPORTED target, or an ALIAS target
  is missing?


CMake Error at CMakeLists.txt:37 (add_library):
  Target "DepthImageToLaserScanROS" links to target
  "image_geometry::image_geometry" but the target was not found.  Perhaps a
  find_package() call is missing for an IMPORTED target, or an ALIAS target
  is missing?


CMake Error at CMakeLists.txt:22 (add_library):
  Target "DepthImageToLaserScan" links to target
  "image_geometry::image_geometry" but the target was not found.  Perhaps a
  find_package() call is missing for an IMPORTED target, or an ALIAS target
  is missing?


CMake Error at /home/jetson_dev/ros2_foxy/install/ament_cmake_gtest/share/ament_cmake_gtest/cmake/ament_add_gtest_executable.cmake:50 (add_executable):
  Target "depthimage_to_laserscan-test" links to target
  "image_geometry::image_geometry" but the target was not found.  Perhaps a
  find_package() call is missing for an IMPORTED target, or an ALIAS target
  is missing?
Call Stack (most recent call first):
  /home/jetson_dev/ros2_foxy/install/ament_cmake_gtest/share/ament_cmake_gtest/cmake/ament_add_gtest_executable.cmake:37 (_ament_add_gtest_executable)
  /home/jetson_dev/ros2_foxy/install/ament_cmake_gtest/share/ament_cmake_gtest/cmake/ament_add_gtest.cmake:68 (ament_add_gtest_executable)
  CMakeLists.txt:87 (ament_add_gtest)


CMake Error at CMakeLists.txt:52 (add_executable):
  Target "depthimage_to_laserscan_node" links to target
  "image_geometry::image_geometry" but the target was not found.  Perhaps a
  find_package() call is missing for an IMPORTED target, or an ALIAS target
  is missing?


CMake Generate step failed.  Build files cannot be regenerated correctly.
---
Failed   <<< depthimage_to_laserscan [6.93s, exited with code 1]

Summary: 0 packages finished [8.00s]
  1 package failed: depthimage_to_laserscan
  1 package had stderr output: depthimage_to_laserscan

```

I would appreciate any guidance you're willing to offer.

**Comment by RNorlie** [comment]
Update: 

Using the package `ros-foxy-depthimage-to-laserscan` resolved my issues.
Still unsure why the devel branch didn't work, but things are working now, so I'll close the issue

Thank you!
