### ISSUE TITLE
could you tell me , how can i publish depth image to laser scan with ros2

### ISSUE THREAD

**Issue by pannatorn6395** [ros-perception/depthimage_to_laserscan#64]

**Comment by pannatorn6395** [comment]
![image](https://user-images.githubusercontent.com/81004343/183000811-805e590d-f592-48aa-a879-7371bd6f8eda.png)
i can't change topic /depth .would you recommend please

**Comment by clalancette** [comment]
Please open questions like this on https://answers.ros.org, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.
