### ISSUE TITLE
How to change scan topic?

### ISSUE THREAD

**Issue by matthewryanburgin191** [ros-perception/depthimage_to_laserscan#65]
Hi,

So i have 2 3d cameras and want to create 2 laserscans.

How do you edit the published topic? For example /front/scan and /rear/scan.
Is there a param? 

Best regards

**Comment by clalancette** [comment]
Please open questions like this on https://answers.ros.org, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.
