### ISSUE TITLE
colcon build ros2 foxy

### ISSUE THREAD

**Issue by EduardoQD** [ros-perception/depthimage_to_laserscan#68]
Hello, 

I'm trying to install this package into my workspace in ROS2 foxy, but when I make colcon build. I receive this message on the terminal:
eduardo@eduardo-CM11EBV716W:~/my_ros2_ws/src$ colcon build 

[0.211s] WARNING:colcon.colcon_core.prefix_path.colcon:The path '/home/eduardo/my_ros2_ws/src/depthimage_to_laserscan/install' in the environment variable COLCON_PREFIX_PATH doesn't exist 

[0.250s] WARNING:colcon.colcon_core.package_selection:Some selected packages are already built in one or more underlay workspaces: 

'depthimage_to_laserscan' is in: /opt/ros/foxy 

If a package in a merged underlay workspace is overridden and it installs headers, then all packages in the overlay must sort their include directories by workspace order. Failure to do so may result in build failures or undefined behavior at run time. 

If the overridden package is used by another package in any underlay, then the overriding package in the overlay must be API and ABI compatible or undefined behavior at run time may occur. 

  

If you understand the risks and want to override a package anyways, add the following to the command line: 

--allow-overriding depthimage_to_laserscan 

  

This may be promoted to an error in a future release of colcon-override-check. 

Starting >>> depthimage_to_laserscan 

Starting >>> pu_pubsub 

--- stderr: depthimage_to_laserscan                                                         

CMake Error at CMakeLists.txt:6 (find_package): 

  By not providing "Findcatkin.cmake" in CMAKE_MODULE_PATH this project has 

  asked CMake to find a package configuration file provided by "catkin", but 

  CMake did not find one. 

  

  Could not find a package configuration file provided by "catkin" with any 

  of the following names: 

  

  catkinConfig.cmake 

 catkin-config.cmake 

  

  Add the installation prefix of "catkin" to CMAKE_PREFIX_PATH or set 

  "catkin_DIR" to a directory containing one of the above files.  If "catkin" 

  provides a separate development package or SDK, be sure it has been 

  installed. 

  

  

--- 

Failed   <<< depthimage_to_laserscan [0.34s, exited with code 1] 

Aborted  <<< pu_pubsub [0.38s] 

  

Summary: 0 packages finished [0.50s] 

  1 package failed: depthimage_to_laserscan 

  1 package aborted: pu_pubsub 

  1 package had stderr output: depthimage_to_laserscan

**Comment by clalancette** [comment]
It looks like you are building the default branch.  You need to clone the `ros2` branch and build that one instead.

In the future, for questions like this, please open them on https://answers.ros.org.  That's our central question and answer site.

**Comment by EduardoQD** [comment]
Ok, I create a thread there, because the problems doesn't dissapear. 
https://answers.ros.org/question/413583/colcon-build-depthimage-to-laserscan-in-ros2-foxy/
