### ISSUE TITLE
Scan Height Issue

### ISSUE THREAD

**Issue by SunilSrivatsav9** [ros-perception/depthimage_to_laserscan#69]
I am trying to use depthimage_laserscan package to convert depth image to 2D laser points. I found the package uses scan_height which uses number of rows (default = 1) for scanning the laser points. 

I was trying to find the laser points of the small objects or obstacles in the image, But however its detecting the laser points of the center of the image and fails to detect the smaller obstacles in front of the camera

I tried changing the **`scan_height`** to different values but still gives the laser points of the center of the image.

Can anyone help me I am missing anything ?

**Comment by clalancette** [comment]
Please open questions like this on https://answers.ros.org, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.
