### ISSUE TITLE
Issue in setting Sensor_DATA QoS

### ISSUE THREAD

**Issue by anath93** [ros-perception/depthimage_to_laserscan#78]
https://robotics.stackexchange.com/questions/103441/depth-image-to-laserscan-not-publishing-to-kinect-scan-topic-in-ros2-galactic

I was looking into the post above and trying it out, the node fails to launch. Is there a way around for this ?

**Comment by clalancette** [comment]
Please ask the question on the post itself, as that launch file isn't part of this package.
