### ISSUE TITLE
ros2 humble launch camera error

### ISSUE THREAD

**Issue by Maxine-zzz** [ros-perception/depthimage_to_laserscan#83]
When I remap the topics to fit my camera and launch depthimage_to_laserscan-launch.py, it seems ok, but when I launch my camera at the same time, depthimage_to_laserscan node will die, I can't find out what's the point

**Comment by clalancette** [comment]
Please open questions like this on https://robotics.stackexchange.com/questions/tagged/ros, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.

**Comment by Maxine-zzz** [comment]
Sorry，I don't know how to submit on this platform,I try many times but fail




欣.
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ros-perception/depthimage_to_laserscan"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月31日(星期三) 晚上8:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ros-perception/depthimage_to_laserscan] ros2 humble launch camera error (Issue #83)





 
Please open questions like this on https://robotics.stackexchange.com/questions/tagged/ros, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.
 
Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.
