### ISSUE TITLE
Node is not doing anything on Humble/Jazzy

### ISSUE THREAD

**Issue by Momin-Musa** [ros-perception/depthimage_to_laserscan#87]
I use the OAK-D PRO camera which publishes the /stereo/depth topic. I tried doing `ros2 run depthimage_to_laserscan depthimage_to_laserscan_node --ros-args --remap depth:=/stereo/depth --remap scan:=/scan` while /stereo/depth is being published, but it does not print anything nor publish something on /scan. I tried on Humble and Jazzy but got no results, are those distros supported?

**Comment by clalancette** [comment]
> I tried on Humble and Jazzy but got no results, are those distros supported?

Yes, they are.

Please open questions like this on https://robotics.stackexchange.com/questions/tagged/ros, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.
